-- upgrade --
ALTER TABLE "car" ADD "album_id" INT;
CREATE TABLE IF NOT EXISTS "album" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "name" VARCHAR(64) NOT NULL,
    "emoji" VARCHAR(20) NOT NULL,
    "rebirth_required" INT NOT NULL  DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "goal" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(64) NOT NULL,
  "player" INTEGER NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE,
  "car" INTEGER NOT NULL REFERENCES "car" ("id") ON DELETE CASCADE,
  "current" INT NOT NULL  DEFAULT 0,
  "target" INT NOT NULL,
  "completed" BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE "player" ADD "bolts" INT NOT NULL  DEFAULT 0;
ALTER TABLE "player" ADD "language" SMALLINT NOT NULL  DEFAULT 1;
ALTER TABLE "guildconfig" ADD "language" SMALLINT NOT NULL  DEFAULT 1;
ALTER TABLE "car" ADD CONSTRAINT "fk_car_album_x7f4rlqk" FOREIGN KEY ("album_id") REFERENCES "album" (id) ON DELETE CASCADE;
CREATE TABLE "friendship" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "player1" INTEGER NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE,
    "player2" INTEGER NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE,
    "bestie" BOOLEAN NOT NULL DEFAULT FALSE,
    "since" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "friendshiprequest" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "sender" INTEGER NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE,
    "receiver" INTEGER NOT NULL REFERENCES "player" ("id") ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "carinstance" DROP "limited"

-- downgrade --
ALTER TABLE "player" DROP COLUMN "bolts";
DROP TABLE IF EXISTS "goal"
DROP TABLE IF EXISTS "album";
DROP TABLE IF EXISTS "friendship";
DROP TABLE IF EXISTS "friendshiprequest"
